[package]
name = "effects-1d-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
effects-1d = { path = "../effects-1d" }
effects-1d-common = { path = "../effects-1d-common" }
effects-1d-simulator = { path = "../effects-1d-simulator" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
three-d = { workspace = true }
