[package]
name = "effects-1d-common"
version = "0.1.0"
edition = "2021"

[dependencies]
palette = { workspace = true }
rand = { workspace = true }
snafu = { version = "0.9.1", default-features = false }
pastey = { workspace = true }
micromath = "2.0.0"

# [target.thumbv6m-none-eabi.dependencies]
# micromath = "2.0.0"


[dev-dependencies]
approx = "0.5.1"
