[package]
name = "effects-1d-common"
version = "0.1.0"
edition = "2021"

[dependencies]
palette = { version = "0.7.0", default-features = false, features = ["libm"] }
rand = { version = "0.8.5", default-features = false, features = [
    "small_rng",
    "getrandom",
] }
snafu = { version = "0.7.4", default-features = false, features = [
    "rust_1_46",
] }
paste = "1.0.12"

# [target.thumbv6m-none-eabi.dependencies]
# micromath = "2.0.0"


[dev-dependencies]
approx = "0.5.1"
