[package]
name = "effects-1d-simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
effects-1d-common = { path = "../effects-1d-common" }
rand = "0.8.5"

[dependencies.bevy]
version = "0.11.0-dev"
git = "https://github.com/bevyengine/bevy.git"
rev = "75130bd5ecfe58693b6a6777fd5cee04b6a34489"
default-features = false
features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "default_font",
]
