[package]
name = "effects-1d-simulator"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
effects-1d-common = { path = "../effects-1d-common" }
effects-1d-runtime = { path = "../effects-1d-runtime" }
rand = { workspace = true, features = ["default"] }
tracing = { workspace = true }
three-d = { workspace = true }
web-time = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
